apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: go-example
  replicas: 1 
  template:
    metadata:
      labels:
        app: go-example
    spec:
      containers:
      - name: go-example
        image: 227500/init:0.2
        ports:
        - containerPort: 80
---
kind: Service  
apiVersion: v1
metadata:
  name: go-example
spec:
  selector:
    app: go-example
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 31500
  type: NodePort

